sudo: true
language: javascript
services:
 - docker
before_install:
  - docker pull icambron/luxon
  - ./docker/install
script:
  - gulp ci
  - gulp test
  - gulp coveralls
  - gulp docs
branches:
  only:
    - master
